"""Generate the placeholder Project 4 report.

The finished report will be written outside the codebase, as Project 3's was,
and dropped in at the same path:

    project4/static/project4/report.pdf

This command exists so that path is never empty. A download button that yields
a 404 is worse than one that yields a page saying the report is not written yet,
and it means the download mechanism can be tested before the content exists.
"""

from pathlib import Path

from django.core.management.base import BaseCommand

OUTPUT = (
    Path(__file__).resolve().parents[2] / "static" / "project4" / "report.pdf"
)

LINES = [
    ("Project 4: Preference Elicitation", 20, "bold"),
    ("Human-Centric Artificial Intelligence  |  Group 29", 11, "normal"),
    ("", 8, "normal"),
    ("This is a placeholder.", 13, "bold"),
    ("", 6, "normal"),
    ("The finished report will cover:", 11, "normal"),
    ("", 4, "normal"),
    ("Task 1 - the feature representation chosen for the IMDB 5000 films,", 10, "normal"),
    ("and why, given that utility is linear in those features.", 10, "normal"),
    ("", 4, "normal"),
    ("Task 2 - the Plackett-Luce extension of the Bradley-Terry model to", 10, "normal"),
    ("rankings, its reduction to Bradley-Terry at n = 2, the rejected", 10, "normal"),
    ("rank-breaking alternative, and the estimator for w.", 10, "normal"),
    ("", 4, "normal"),
    ("Task 3 - the full design of the user study: hypothesis, assignment", 10, "normal"),
    ("and counterbalancing, measures, recruitment, ethics and data", 10, "normal"),
    ("protection, and the analysis plan.", 10, "normal"),
    ("", 8, "normal"),
    ("The interface for Task 4 is already implemented and can be reached", 10, "normal"),
    ("from the project landing page.", 10, "normal"),
]


class Command(BaseCommand):
    help = "Write the placeholder Project 4 report PDF"

    def handle(self, *args, **options):
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        fig = plt.figure(figsize=(8.27, 11.69))  # A4 portrait
        fig.patch.set_facecolor("white")

        y = 0.93
        for text, size, weight in LINES:
            if text:
                fig.text(0.11, y, text, fontsize=size, fontweight=weight,
                         color="#002429", family="DejaVu Sans")
            y -= size / 500 + 0.012

        fig.text(0.11, 0.05,
                 "Generated by manage.py build_project4_report - replace with the real report.",
                 fontsize=8, color="#58686e", family="DejaVu Sans")

        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(OUTPUT, format="pdf")
        plt.close(fig)

        size_kb = OUTPUT.stat().st_size / 1024
        self.stdout.write(self.style.SUCCESS(
            f"Wrote {OUTPUT} ({size_kb:.0f} KB)"
        ))
