# Generated by Django 5.2.17 on 2026-08-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project4", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studysession",
            name="estimated_w",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
