# Generated by Django 5.2.17 on 2026-09-11 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project4", "0002_studysession_estimated_w"),
    ]

    operations = [
        migrations.AddField(
            model_name="studysession",
            name="questionnaire",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Trial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("design", models.CharField(max_length=16)),
                ("block", models.PositiveSmallIntegerField()),
                ("index", models.PositiveSmallIntegerField()),
                ("ordering", models.JSONField()),
                ("milliseconds", models.PositiveIntegerField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trials",
                        to="project4.studysession",
                    ),
                ),
            ],
            options={
                "ordering": ["session_id", "block", "index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "block", "index"), name="one_row_per_trial"
                    )
                ],
            },
        ),
    ]
