# Generated by Django 5.2.17 on 2026-08-21 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("n_rows", models.PositiveIntegerField()),
                ("n_columns", models.PositiveIntegerField()),
                ("column_names", models.JSONField()),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("algorithm", models.CharField(max_length=32)),
                ("algorithm_label", models.CharField(max_length=64)),
                ("parameter_name", models.CharField(max_length=64)),
                ("target", models.CharField(max_length=255)),
                ("test_size", models.FloatField()),
                ("score_name", models.CharField(max_length=32)),
                ("score_label", models.CharField(max_length=64)),
                ("best_parameter", models.CharField(max_length=64)),
                ("best_score", models.FloatField()),
                ("training_rows", models.PositiveIntegerField()),
                ("testing_rows", models.PositiveIntegerField()),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="project1.dataset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameter_value", models.CharField(max_length=64)),
                ("score", models.FloatField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="project1.trainingrun",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
